theme: jekyll-theme-slate
owner:
  name: Tyler Landle
  email: tlandle3@gatech.edu
  # Do not include the @ symbol in your Twitter username
  linkedin: (https://www.linkedin.com/in/tyler-landle/)
  github: tlandle
