title: Tyler Landle
author:
  name: Tyler Landle
  email: "tlandle3@gatech.edu"


relative_links:
  enabled: true
  collections: true

minima:
  social_links:
    linkedin: tyler-landle
    github: tlandle
    
show_excerpts: true
    
header_pages:
  - cv.md

theme: jeykll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme

