title: Academic Website of Tyler Landle
locale: en_US
relative_links:
  enabled: true
  collections: true
owner:
  name: Tyler Landle
  email: tlandle3@gatech.edu
  linkedin: (https://www.linkedin.com/in/tyler-landle/)
  github: tlandle

theme: jekyll-theme-slate

