title: Tyler Landle
author: Tyler Landle 
email: 
  - "tlandle3@gatech.edu"


relative_links:
  enabled: true
  collections: true

#minima:
  #social_links:
    #linkedin: tyler-landle
    #github: tlandle
    
linkedin_username: tyler-landle
github_username: tlandle

show_excerpts: true
    
header_pages:
  - cv.md
  - papers_and_talks.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

