title: Tyler Landle
locale: en_US
author:
  name: Tyler Landle
  email: tlandle3@gatech.edu
relative_links:
  enabled: true
  collections: true
social_links:
  linkedin: (https://www.linkedin.com/in/tyler-landle/)
  github: tlandle

theme: jekyll-theme-slate

