title: Tyler Landle
locale: en_US
author:
  name: Tyler Landle
  email: tlandle3@gatech.edu
relative_links:
  enabled: true
  collections: true
minima:
  social_links:
    linkedin: tyler-landle
    github: tlandle

theme: minima

